### ISSUE TITLE
Event handling (Client Query) The command 'auth' is unknown

### ISSUE THREAD

**Issue by ckocyigit** [benediktschmitt/py-ts3#100]
When trying the Example Script for the Client Query Iam getting this error:

Traceback (most recent call last):
  File "C:/Users/USER/Desktop/TSVoIP/main.py", line 33, in <module>
    ts3conn.exec_("auth", apikey=isSet*******************************)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python38-32\lib\site-packages\ts3\query.py", line 668, in exec_
    q = self.query(cmd, *options, **params)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python38-32\lib\site-packages\ts3\query.py", line 734, in query
    raise TS3InvalidCommandError(cmd, self.COMMAND_SET)
ts3.query.TS3InvalidCommandError: The command 'auth' is unknown.

**Comment by ckocyigit** [comment]
Trying the command auth apikey="*********" with putty works

**Comment by WhOoKie** [comment]
I believe the library contains a frozenset of available query commands. When running a command, the library checks the set if the command exists. Very possible that command hasnt been added yet, as the it is quite new.
