### ISSUE TITLE
Instillation error

### ISSUE THREAD

**Issue by Ahmed-90** [benediktschmitt/py-ts3#15]
Hi,
getting his error when trying to install i read in #2 its python 2 (aka old version) error but am on 3.4.2.. any idea?

```
Collecting ts3
  Using cached ts3-0.6.3.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "C:\Users\Ahmed90\AppData\Local\Temp\pycharm-packaging0.tmp\ts3\ts3\__init__.py", line 45, in <module>
        import query
    ImportError: No module named 'query'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "C:\Users\Ahmed90\AppData\Local\Temp\pycharm-packaging0.tmp\ts3\setup.py", line 28, in <module>
        from ts3 import __version__
      File "C:\Users\Ahmed90\AppData\Local\Temp\pycharm-packaging0.tmp\ts3\ts3\__init__.py", line 51, in <module>
        from . import query
      File "C:\Users\Ahmed90\AppData\Local\Temp\pycharm-packaging0.tmp\ts3\ts3\query.py", line 39, in <module>
        import blinker
    ImportError: No module named 'blinker'
    
    ----------------------------------------

Command "python setup.py egg_info" failed with error code 1 in C:\Users\Ahmed90\AppData\Local\Temp\pycharm-packaging0.tmp\ts3
```

Thanks

**Comment by Ahmed-90** [comment]
ummm it turned out that i need to install blinker first (manually)
