### ISSUE TITLE
servernotifyregister

### ISSUE THREAD

**Issue by Multivit4min** [benediktschmitt/py-ts3#18]
Hey i have a new Problem!

I use Python3.4
I get this stacktrace when i try to register a event

Traceback (most recent call last):
  File "start.py", line 6, in <module>
    bot.run()
  File "/home/python/ts3bot/bot.py", line 36, in run
    'textprivate'
  File "/home/python/ts3bot/bot.py", line 45, in registerEvents
    self.ts3conn.servernotifyregister(event=ev)
  File "/home/python/ts3bot/ts3/commands.py", line 3664, in servernotifyregister
    return self._return_proxy("servernotifyregister", cparams, uparams, options)
  File "/home/python/ts3bot/ts3/query.py", line 647, in _return_proxy
    self, command, common_parameters, unique_parameters, options)
  File "/home/python/ts3bot/ts3/query.py", line 613, in send
    self._telnet_conn.write(query_command)
AttributeError: 'NoneType' object has no attribute 'write'

**Comment by Multivit4min** [comment]
My Fault Sorry
