### ISSUE TITLE
Connection Reset by Peer / Broken Pipe errors randomly started throwing

### ISSUE THREAD

**Issue by chrisengel** [benediktschmitt/py-ts3#42]
I had some basic code for connecting to a server and making a bot post. It worked fine, but then a few hours ago it starts throwing the following errors:
```

File "/usr/local/lib/python3.4/dist-packages/ts3/query.py", line 155, in __init__
    self.open(host, port)
  File "/usr/local/lib/python3.4/dist-packages/ts3/query.py", line 205, in open
    self._telnet_conn.read_until(b"\n\r")
  File "/usr/lib/python3.4/telnetlib.py", line 317, in read_until
    self.fill_rawq()
  File "/usr/lib/python3.4/telnetlib.py", line 526, in fill_rawq
    buf = self.sock.recv(50)
ConnectionResetError: [Errno 104] Connection reset by peer
Exception ignored in: <bound method TS3Connection.__del__ of <ts3.query.TS3Connection object at 0x7fdf902a18d0>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/ts3/query.py", line 250, in __del__
    self.close()
  File "/usr/local/lib/python3.4/dist-packages/ts3/query.py", line 221, in close
    self._telnet_conn.write(b"quit\n\r")
  File "/usr/lib/python3.4/telnetlib.py", line 292, in write
    self.sock.sendall(buffer)
BrokenPipeError: [Errno 32] Broken pipe

```

Nothing on the VPS has changed, the TS server's serverquery works fine manually via telnet. The TS server hasn't been upgraded today -- so im not sure what is going on.

**Comment by benediktschmitt** [comment]
The ts3 server closes connections automatic after 10 minutes, if no data has been received from the client. So (if you are not already doing this) you must call ``ts3conn.send_keepalive()`` at least once each ten minutes. (https://github.com/benediktschmitt/py-ts3/blob/master/ts3/examples/hello_bot.py#L42)

Can you provide a small code snippet which produces the bug?

**Comment by benediktschmitt** [comment]
Please reopen, if not fixed.
