### ISSUE TITLE
installation broken

### ISSUE THREAD

**Issue by kakulukia** [benediktschmitt/py-ts3#45]
```
Collecting ts3
  Downloading ts3-1.0.6.tar.gz (40kB)
    100% |████████████████████████████████| 40kB 1.3MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-d6QLSD/ts3/setup.py", line 28, in <module>
        from ts3 import __version__
      File "ts3/__init__.py", line 45, in <module>
        import query
      File "ts3/query.py", line 39, in <module>
        from commands import TS3Commands
      File "ts3/commands.py", line 79
        def banadd(self, *, ip=None, name=None, uid=None, time=None, banreason=None):
                          ^
    SyntaxError: invalid syntax

    ----------------------------------------```

**Comment by kakulukia** [comment]
never mind .. tho i created a python3 virtualenv something went wrong and thus python2 could not install the package ..
