### ISSUE TITLE
Strange error

### ISSUE THREAD

**Issue by Backdoorek** [benediktschmitt/py-ts3#58]
While making a python program using this library, I encountered an error.
```
<ts3.response.TS3QueryResponse object at 0x0000026492BEE4A8>
Exception ignored in: <bound method TS3BaseConnection.__del__ of <ts3.query.TS3Connection object at 0x0000026492E5C4A8>>
Traceback (most recent call last):
  File "C:\Users\Krystian\AppData\Local\Programs\Python\Python36\lib\site-packages\ts3\query.py", line 250, in __del__
  File "C:\Users\Krystian\AppData\Local\Programs\Python\Python36\lib\site-packages\ts3\query.py", line 230, in close
  File "C:\Users\Krystian\AppData\Local\Programs\Python\Python36\lib\logging\__init__.py", line 1294, in debug
  File "C:\Users\Krystian\AppData\Local\Programs\Python\Python36\lib\logging\__init__.py", line 1442, in _log
  File "C:\Users\Krystian\AppData\Local\Programs\Python\Python36\lib\logging\__init__.py", line 1452, in handle
  File "C:\Users\Krystian\AppData\Local\Programs\Python\Python36\lib\logging\__init__.py", line 1514, in callHandlers
  File "C:\Users\Krystian\AppData\Local\Programs\Python\Python36\lib\logging\__init__.py", line 863, in handle
  File "C:\Users\Krystian\AppData\Local\Programs\Python\Python36\lib\logging\__init__.py", line 1069, in emit
  File "C:\Users\Krystian\AppData\Local\Programs\Python\Python36\lib\logging\__init__.py", line 1059, in _open
NameError: name 'open' is not defined

Process finished with exit code 0
```
Here is my code
```python
import ts3, json, logging

config = json.load(open('configPrivate.json'))

class UpdaterBot():
    def __init__(self):
        logging.basicConfig(filename='actions.log', filemode='w+', level='DEBUG', format='%(asctime)s %(message)s')
        self.loadConfig()
        self.connect()

    def loadConfig(self):
        logging.debug('Loading config...')

        self.host = config['TeamSpeak']['Host']
        logging.debug(
            'Loaded host as {}'.format(self.host)
        )

        self.port = config['TeamSpeak']['QPort']
        logging.debug(
            'Loaded Query Port as {}'.format(self.port)
        )

        self.login = config['TeamSpeak']['Login']
        logging.debug(
            'Loaded Login as {}'.format(self.login)
        )

        self.passwd = config['TeamSpeak']['Passwd']
        logging.debug(
            'Loaded password as {}'.format(self.passwd)
        )

        self.sid = config['TeamSpeak']['SID']
        logging.debug(
            'Loaded server id as {}'.format(self.sid)
        )

    def connect(self):
        try:
            logging.info('Trying to connect to server')
            self.ts3conn = ts3.query.TS3Connection(
                host=self.host,
                port=self.port
            )
            logging.info('Trying to login')
            self.ts3conn.login(
                client_login_name=self.login,
                client_login_password=self.passwd
            )
            self.ts3conn.use(sid=self.sid)
        except ts3.query.TS3QueryError as err:
            logging.error('Unable to connect to server')
            logging.error(err.resp.error["msg"])

    def queryTsData(self):
        data = self.ts3conn.serverinfo()
        print(data)

    def basicUpdate(self, tsData):
        pass

if __name__ == '__main__':
    k = UpdaterBot()
    k.queryTsData()

```
Where is a problem?

**Comment by benediktschmitt** [comment]
This is a problem with the logging module: https://bugs.python.org/issue26789

You should be able to avoid this bug by closing the connection gracefully, i.e. calling *ts3conn.close()* or by using the context manager. Something like:
```Python
if __name__ == "__main__":
  k = UpdaterBot()
  try:
    k.queryTsData():
  finally:
    k.ts3conn.close()
```
should work.

**Comment by Backdoorek** [comment]
thanks for help
