### ISSUE TITLE
How to check if client_Id is invalid?

### ISSUE THREAD

**Issue by Bluscream** [benediktschmitt/py-ts3#83]
```py
        clientlist = ts3conn.exec_("clientlist")
        for client in clientlist:
                try:
                        if (client["client_type"] != "0"): continue
                except query.TS3QueryError as err: logger.error(err.args[0].all()); continue
                except: logger.error(format_exc()); continue
```

This does not seem to work, I only get
```
2019-02-09 15:46:00,608 - root - ERROR - Traceback (most recent call last):
  File "P:\Projects\Python\QueryVersionSniffer\__init__.py", line 83, in <module>
    clientinfo = ts3conn.query("clientinfo").params(clid=client["clid"]).first()
  File "C:\Program Files\Python3\lib\site-packages\ts3\query_builder.py", line 208, in first
    resp = self.fetch()
  File "C:\Program Files\Python3\lib\site-packages\ts3\query_builder.py", line 196, in fetch
    return self._ts3conn.exec_query(self)
  File "C:\Program Files\Python3\lib\site-packages\ts3\query.py", line 755, in exec_query
    return self._wait_for_resp(timeout=timeout)
  File "C:\Program Files\Python3\lib\site-packages\ts3\query.py", line 621, in _wait_for_resp
    raise TS3QueryError(resp)
ts3.query.TS3QueryError: error id 512: invalid clientID

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "P:\Projects\Python\QueryVersionSniffer\__init__.py", line 96, in <module>
    except query.TS3QueryError as err: logger.error(err.args[0].all()); continue
AttributeError: 'TS3QueryResponse' object has no attribute 'all'
```

**Comment by AdorablePotato** [comment]
You probably found/fixed the error in the meantime, but if not:

The TS3QueryError has the response set as attribute, so you get the error id and message from there (instead of *err.args[0].all()*):
```Python
except TS3QueryError as err:
    err_id = err.resp.error["id"]
    err_msg = err.resp.error["msg"]
```
I hope this works for you. 

The shown error seems to originate from somewhere else. I tried "clientlist" and "clientinfo" and both commands worked as expected:
```Python
with ts3.query.TS3ServerConnection(URI) as ts3conn:
    ts3conn.exec_("use", sid=1)

    clientlist = ts3conn.exec_("clientlist")
    for client in clientlist:
        pprint(client)

        info = ts3conn.exec_("clientinfo", clid=client["clid"])
        pprint(info.parsed)

```

**Comment by Bluscream** [comment]
Thanks
